flowchart LR

    False["<code>False</code>"] ~~~ 1["Bit 1\n\n<code>0</code>"] --- 2["Bit 2\n\n<code>0</code>"] --- 3["Bit 3\n\n<code>0</code>"] --- 4["Bit 4\n\n<code>0</code>"] --- 5["Bit 5\n\n<code>0</code>"] --- 6["Bit 6\n\n<code>0</code>"] --- 7["Bit 7\n\n<code>0</code>"] --- 8["Bit 8\n\n<code>0</code>"]

    style False fill:lightgray,stroke-width:0px

    style 1 fill:lightpink,stroke-width:0px
    style 2 fill:lightpink,stroke-width:0px
    style 3 fill:lightpink,stroke-width:0px
    style 4 fill:lightpink,stroke-width:0px
    style 5 fill:lightpink,stroke-width:0px
    style 6 fill:lightpink,stroke-width:0px
    style 7 fill:lightpink,stroke-width:0px
    style 8 fill:lightpink,stroke-width:0px