flowchart LR

    False1["<code>True</code>"] ~~~ 11["Bit 1\n\n<code>1</code>"] --- 12["Bit 2\n\n<code>0</code>"] --- 13["Bit 3\n\n<code>0</code>"] --- 14["Bit 4\n\n<code>0</code>"] --- 15["Bit 5\n\n<code>0</code>"] --- 16["Bit 6\n\n<code>0</code>"] --- 17["Bit 7\n\n<code>0</code>"] --- 18["Bit 8\n\n<code>0</code>"]

    More["..."]

    False2["<code>True</code>"] ~~~ 21["Bit 1\n\n<code>1</code>"] --- 22["Bit 2\n\n<code>1</code>"] --- 23["Bit 3\n\n<code>1</code>"] --- 24["Bit 4\n\n<code>1</code>"] --- 25["Bit 5\n\n<code>1</code>"] --- 26["Bit 6\n\n<code>1</code>"] --- 27["Bit 7\n\n<code>1</code>"] --- 28["Bit 8\n\n<code>1</code>"]

    style False1 fill:lightgray,stroke-width:0px
    style False2 fill:lightgray,stroke-width:0px

    style More fill:white,stroke-width:0px

    style 11 fill:lightgreen,stroke-width:0px
    style 12 fill:lightpink,stroke-width:0px
    style 13 fill:lightpink,stroke-width:0px
    style 14 fill:lightpink,stroke-width:0px
    style 15 fill:lightpink,stroke-width:0px
    style 16 fill:lightpink,stroke-width:0px
    style 17 fill:lightpink,stroke-width:0px
    style 18 fill:lightpink,stroke-width:0px

    style 21 fill:lightgreen,stroke-width:0px
    style 22 fill:lightgreen,stroke-width:0px
    style 23 fill:lightgreen,stroke-width:0px
    style 24 fill:lightgreen,stroke-width:0px
    style 25 fill:lightgreen,stroke-width:0px
    style 26 fill:lightgreen,stroke-width:0px
    style 27 fill:lightgreen,stroke-width:0px
    style 28 fill:lightgreen,stroke-width:0px