

flowchart TB
    
    Datentypen["<b>Datentypen</b> der Programmiersprache <i>Python</i>"]

    Datentypen --> Komplex["<b>Komplexe</b> Datentypen"]

    Komplex --> Sammlung["Sammlungen"]

    Sammlung --> Abbildung["Abbildungen"]

    Abbildung --> dict["<i>(mutable)</i><br/><code>dict</code>"]

    style Datentypen fill:black,color:white,stroke-width:0px
    style Komplex fill:black,color:white,stroke-width:0px

    style Sammlung fill:lightgray,stroke-width:0px
    style Abbildung fill:lightgray,stroke-width:0px

    style dict fill:lightgreen,stroke-width:0px
    