

flowchart TB
    
    Datentypen["<b>Datentypen</b> der Programmiersprache <i>Python</i>"]

    Datentypen --> Komplex["<b>Komplexe</b> Datentypen"]

    Komplex --> Klassen

    Klassen --> Klasse["<code>class</code>"]

    style Datentypen fill:black,color:white,stroke-width:0px
    style Komplex fill:black,color:white,stroke-width:0px

    style Klassen fill:lightgray,stroke-width:0px
  
    style Klasse fill:lightpink,stroke-width:0px
