flowchart

    Funktionen

    Funktionen --> Str["<code>str(...)</code>"]
    Funktionen --> Type["<code>type(...)</code>"]
    Funktionen --> Print["<code>print(...)</code>"]
    Funktionen --> Input["<code>input(...)</code>"]

    style Funktionen fill:black,color:white,stroke-width:0px

    style Str fill:khaki,stroke-width:0px
    style Type fill:skyblue,stroke-width:0px
    style Print fill:lightgreen,stroke-width:0px
    style Input fill:lightpink,stroke-width:0px
