flowchart

    Funktionen --> Typbestimmung["Funktion für<br/><b>Typbestimmung</b>"]
    Funktionen --> Typkonvertierung["Funktion für<br/><b>Typkonvertierung</b>"]
    Funktionen --> Zahlenfunktionen["Funktion für<br/><b>Zahlen</b>"]
    Funktionen --> Zeichenkettenfunktionen["Funktion für<br/><b>Zeichenketten</b>"]
    Funktionen --> EA["Funkionen für<br/><b>Eingabe/Ausgabe</b>"]

    style Funktionen fill:black,color:white,stroke-width:0px

    style Typbestimmung fill:lightgray,stroke-width:0px
    style Typkonvertierung fill:lightgray,stroke-width:0px
    style Zahlenfunktionen fill:lightgray,stroke-width:0px
    style Zeichenkettenfunktionen fill:lightgray,stroke-width:0px
    style EA fill:lightgray,stroke-width:0px
