flowchart

    Funktionen --> Typbestimmung
    Funktionen --> Typkonvertierung
    Funktionen --> Zahlenfunktionen
    Funktionen --> EA["Eingabe/Ausgabe"]

    style Funktionen fill:black,color:white,stroke-width:0px

    style Typbestimmung fill:lightgray,stroke-width:0px
    style Typkonvertierung fill:lightgray,stroke-width:0px
    style Zahlenfunktionen fill:lightgray,stroke-width:0px
    style EA fill:lightgray,stroke-width:0px
