flowchart

    Funktionen --> Typbestimmung

    Typbestimmung  --> Type["<code>type(...)</code>"]

    style Funktionen fill:black,color:white,stroke-width:0px

    style Typbestimmung fill:lightgray,stroke-width:0px

    style Type fill:khaki,stroke-width:0px
    