flowchart

    Funktionen --> Typkonvertierung

    Typkonvertierung --> Bool["<code>bool(...)</code>"]
    Typkonvertierung --> Int["<code>int(...)</code>"]
    Typkonvertierung --> Float["<code>float(...)</code>"]
    Typkonvertierung --> Complex["<code>complex(...)</code>"]
    Typkonvertierung --> Str["<code>str(...)</code>"]

    style Funktionen fill:black,color:white,stroke-width:0px

    style Typkonvertierung fill:lightgray,stroke-width:0px

    style Bool fill:skyblue,stroke-width:0px
    style Int fill:skyblue,stroke-width:0px
    style Float fill:skyblue,stroke-width:0px
    style Complex fill:skyblue,stroke-width:0px
    style Str fill:skyblue,stroke-width:0px
