flowchart

    Funktionen --> Zahlenfunktionen

    Zahlenfunktionen --> Abs["<code>abs(...)</code>"]
    Zahlenfunktionen --> Pow["<code>pow(...)</code>"]

    style Funktionen fill:black,color:white,stroke-width:0px

    style Zahlenfunktionen fill:lightgray,stroke-width:0px

    style Abs fill:lightgreen,stroke-width:0px
    style Pow fill:lightgreen,stroke-width:0px
