flowchart LR

    München ---|170km| Passau ---|88km| Wels

    München ---|144km| Salzburg ---|109km| Wels ---|27km| Linz ---|183km| Wien

    Salzburg ---|113km| Passau

    Salzburg ---|138km| Liezen ---|119km| Graz

    Villach ---|184km| Liezen

    Liezen ---|87km| Wels

    Salzburg ---|183km| Villach ---|39km| Klagenfurt ---|139km| Graz

    Graz ---|198km| Wien