flowchart

    Befehle["<b>Vereinfachter Befehlssatz</b> einer<br/>zentralen Recheneinheit (CPU)"]

    Befehle --> Transfer["<b>Speicher</b>befehle"]
    Befehle --> Arithmetisch["<b>Arithmetik</b>befehle"]
    Befehle --> Logisch["<b>Logik</b>befehle"]
    Befehle --> Vergleich["<b>Vergleichs</b>befehle"]
    Befehle --> Sprung["<b>Sprung</b>befehle"]

    style Befehle fill:black,color:white,stroke-width:0px

    style Transfer fill:lightgray,stroke-width:0px
    style Arithmetisch fill:lightgray,stroke-width:0px
    style Logisch fill:lightgray,stroke-width:0px
    style Vergleich fill:lightgray,stroke-width:0px
    style Sprung fill:lightgray,stroke-width:0px
