flowchart

    Befehle["<b>Vereinfachter Befehlssatz</b> einer<br/>zentralen Recheneinheit (CPU)"]

    Befehle --> Transfer["<b>Speicher</b>befehle"]

    Transfer --> MOV["<code>MOV a b</code><br/>Datenaustausch zwischen Hauptspeicher<br/>und einem Prozessorregister"]

    style Befehle fill:black,color:white,stroke-width:0px

    style Transfer fill:lightgray,stroke-width:0px

    style MOV fill:khaki,stroke-width:0px
