flowchart

    Befehle["<b>Vereinfachter Befehlssatz</b> einer<br/>zentralen Recheneinheit (CPU)"]

    Befehle --> Vergleich["<b>Vergleichs</b>befehle"]

    Vergleich --> CMP["<code>CMP a b</code><br/>Vergleich der Inhalte<br/>zweier Prozessorregister"]

    style Befehle fill:black,color:white,stroke-width:0px

    style Vergleich fill:lightgray,stroke-width:0px

    style CMP fill:lightpink,stroke-width:0px
