flowchart

    Operatoren

    Operatoren --> Bool["Operatoren für <b>Wahrheitswerte</b>"]
    Operatoren --> Num["Operatoren für <b>Zahlen</b>"]
    Operatoren --> Str["Operatoren für <b>Zeichenketten</b>"]
    Operatoren --> More["..."]

    style Operatoren fill:black,color:white,stroke-width:0px

    style Bool fill:lightgray,stroke-width:0px
    style Num fill:lightgray,stroke-width:0px
    style Str fill:lightgray,stroke-width:0px
    style More fill:lightgray,stroke-width:0px
    