flowchart TB

    Operatoren["<b>Operatoren</b> der Programmiersprache <i>Python</i>"]

    Operatoren --> Berechnung

    Berechnung --> Boolsch["<b>Boolsche</b> Operatoren"]

    Boolsch --> Logik["<b>Logik</b>operatoren"]

    Logik --> And["<code>a and b</code>"]
    Logik --> Or["<code>a or b</code>"]
    Logik --> Not["<code>not a</code>"]
    
    style Operatoren fill:black,color:white,stroke-width:0px
    style Berechnung fill:black,color:white,stroke-width:0px

    style Boolsch fill:lightgray,stroke-width:0px
    style Logik fill:lightgray,stroke-width:0px

    style And fill:khaki,stroke-width:0px
    style Or fill:khaki,stroke-width:0px
    style Not fill:khaki,stroke-width:0px