flowchart TB

    Operatoren["<b>Operatoren</b> der Programmiersprache <i>Python</i>"]

    Operatoren --> Berechnung

    Berechnung --> Boolsch["<b>Boolsche</b> Operatoren"]

    Boolsch --> Identity["<b>Identitäts</b>operatoren"]

    Identity --> Is["<code>a is b</code>"]
    Identity --> IsNot["<code>a is not b</code>"]

    style Operatoren fill:black,color:white,stroke-width:0px
    style Berechnung fill:black,color:white,stroke-width:0px

    style Boolsch fill:lightgray,stroke-width:0px
    style Identity fill:lightgray,stroke-width:0px

    style Is fill:khaki,stroke-width:0px
    style IsNot fill:khaki,stroke-width:0px
    