flowchart TB

    Operatoren["<b>Operatoren</b> der Programmiersprache <i>Python</i>"]

    Operatoren --> Berechnung

    Berechnung --> Boolsch["<b>Boolsche</b> Operatoren"]

    Boolsch --> Vergleich["<b>Vergleichs</b>operatoren"]

    Vergleich --> Equal["<code>a == b</code>"]
    Vergleich --> NotEqual["<code>a != b</code>"]
    Vergleich --> GreaterThan["<code>a > b</code>"]
    Vergleich --> SmallerThan["<code>a < b</code>"]
    Vergleich --> GreaterThanOrEqualTo["<code>a >= b</code>"]
    Vergleich --> SmallerThanOrEqualTo["<code>a <= b</code>"]

    style Operatoren fill:black,color:white,stroke-width:0px
    style Berechnung fill:black,color:white,stroke-width:0px

    style Boolsch fill:lightgray,stroke-width:0px
    style Vergleich fill:lightgray,stroke-width:0px

    style Equal fill:khaki,stroke-width:0px
    style NotEqual fill:khaki,stroke-width:0px
    style GreaterThan fill:khaki,stroke-width:0px
    style SmallerThan fill:khaki,stroke-width:0px
    style GreaterThanOrEqualTo fill:khaki,stroke-width:0px
    style SmallerThanOrEqualTo fill:khaki,stroke-width:0px